[functions.livekit-token]
verify_jwt = false

[functions.livekit-guest-token]
verify_jwt = false

[functions.import-ezitrack-daily-report]
verify_jwt = false

[functions.codex-execute-tool]
verify_jwt = false

[functions.codex-process-input]
verify_jwt = false

[functions.check-time-tracking]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-direct-email]
verify_jwt = false

[functions.content-studio-analyze-image]
verify_jwt = false

[functions.process-scheduled-actions]
verify_jwt = false

[functions.export-timesheet]
enabled = true
verify_jwt = true
import_map = "./functions/export-timesheet/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/export-timesheet/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/export-timesheet/*.html" ]
