import { supabase } from "../../../lib/supabase/client";

export const SERVICE_WORKER_URL = "/service-worker.js";

const VAPID_PUBLIC_KEY = import.meta.env.VITE_VAPID_PUBLIC_KEY as
  | string
  | undefined;

function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; i += 1) {
    outputArray[i] = rawData.charCodeAt(i);
  }

  return outputArray;
}

export function getPushSupportError() {
  if (typeof window === "undefined" || typeof navigator === "undefined") {
    return "Push notifications are only available in a browser.";
  }

  const isLocalhost =
    window.location.hostname === "localhost" ||
    window.location.hostname === "127.0.0.1";

  if (!window.isSecureContext && !isLocalhost) {
    return "Push notifications require HTTPS or localhost.";
  }

  if (!("serviceWorker" in navigator)) {
    return "Service workers are not supported in this browser.";
  }

  if (!("PushManager" in window)) {
    return "Push notifications are not supported in this browser.";
  }

  if (!("Notification" in window)) {
    return "Notifications are not supported in this browser.";
  }

  return "";
}

export function getPushConfigurationError() {
  return VAPID_PUBLIC_KEY ? "" : "Missing VITE_VAPID_PUBLIC_KEY.";
}

/** Register the service worker as early as possible (no permission prompt). */
export async function ensureServiceWorkerReady() {
  const supportError = getPushSupportError();
  if (supportError) return null;

  await navigator.serviceWorker.register(SERVICE_WORKER_URL, {
    scope: "/",
  });

  return navigator.serviceWorker.ready;
}

export async function getBrowserPushSubscription() {
  const supportError = getPushSupportError();
  if (supportError) return null;

  const registration = await ensureServiceWorkerReady();
  if (!registration) return null;

  return registration.pushManager.getSubscription();
}

async function persistPushSubscription(params: {
  userId: string;
  organizationId: string;
  subscription: PushSubscription;
}) {
  const json = params.subscription.toJSON();

  if (!json.endpoint || !json.keys?.p256dh || !json.keys?.auth) {
    throw new Error("Invalid push subscription generated by browser.");
  }

  const { error } = await supabase.from("push_subscriptions").upsert(
    {
      organization_id: params.organizationId,
      user_id: params.userId,
      endpoint: json.endpoint,
      p256dh: json.keys.p256dh,
      auth: json.keys.auth,
      user_agent: navigator.userAgent,
      is_active: true,
      updated_at: new Date().toISOString(),
    },
    {
      onConflict: "user_id,endpoint",
    },
  );

  if (error) throw error;

  return params.subscription;
}

/**
 * Re-sync an existing browser subscription to Supabase (after login or app reload).
 * Does not show the permission prompt.
 */
export async function syncPushSubscriptionWithServer(params: {
  userId: string;
  organizationId: string;
}) {
  const supportError = getPushSupportError();
  if (supportError) return null;

  const configurationError = getPushConfigurationError();
  if (configurationError) return null;

  if (typeof Notification === "undefined" || Notification.permission !== "granted") {
    return null;
  }

  const registration = await ensureServiceWorkerReady();
  if (!registration) return null;

  const vapidPublicKey = VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) return null;

  let subscription = await registration.pushManager.getSubscription();

  if (!subscription) {
    subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
    });
  }

  return persistPushSubscription({
    userId: params.userId,
    organizationId: params.organizationId,
    subscription,
  });
}

export async function registerPushNotifications(params: {
  userId: string;
  organizationId: string;
}) {
  const supportError = getPushSupportError();
  if (supportError) throw new Error(supportError);

  const configurationError = getPushConfigurationError();
  if (configurationError) throw new Error(configurationError);
  const vapidPublicKey = VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) throw new Error("Missing VITE_VAPID_PUBLIC_KEY.");

  const permission = await Notification.requestPermission();

  if (permission !== "granted") {
    throw new Error("Notification permission was not granted.");
  }

  const registration = await ensureServiceWorkerReady();
  if (!registration) {
    throw new Error("Service worker is not available.");
  }

  const existingSubscription = await registration.pushManager.getSubscription();

  const subscription =
    existingSubscription ??
    (await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
    }));

  return persistPushSubscription({
    userId: params.userId,
    organizationId: params.organizationId,
    subscription,
  });
}

export async function unregisterPushNotifications(params: {
  userId: string;
}) {
  const supportError = getPushSupportError();
  if (supportError) throw new Error(supportError);

  if ("serviceWorker" in navigator) {
    const registration = await navigator.serviceWorker.getRegistration("/");
    const subscription = await registration?.pushManager.getSubscription();
    if (subscription) {
      await subscription.unsubscribe();
    }
  }

  const { error } = await supabase
    .from("push_subscriptions")
    .update({ is_active: false, updated_at: new Date().toISOString() })
    .eq("user_id", params.userId);

  if (error) throw error;
}

/** True when this browser has an active push subscription saved for the user. */
export async function checkPushEnabledForUser(userId: string) {
  const browserSubscription = await getBrowserPushSubscription();
  if (!browserSubscription) return false;

  const { data, error } = await supabase
    .from("push_subscriptions")
    .select("id")
    .eq("user_id", userId)
    .eq("is_active", true)
    .eq("endpoint", browserSubscription.endpoint)
    .limit(1);

  if (error) {
    console.warn("PUSH STATUS CHECK ERROR:", error.message);
    return true;
  }

  return (data?.length ?? 0) > 0;
}
