import { supabase } from "../../../lib/supabase/client";

const VAPID_PUBLIC_KEY = import.meta.env.VITE_VAPID_PUBLIC_KEY as
  | string
  | undefined;

function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; i += 1) {
    outputArray[i] = rawData.charCodeAt(i);
  }

  return outputArray;
}

export function getPushSupportError() {
  if (typeof window === "undefined" || typeof navigator === "undefined") {
    return "Push notifications are only available in a browser.";
  }

  const isLocalhost =
    window.location.hostname === "localhost" ||
    window.location.hostname === "127.0.0.1";

  if (!window.isSecureContext && !isLocalhost) {
    return "Push notifications require HTTPS or localhost.";
  }

  if (!("serviceWorker" in navigator)) {
    return "Service workers are not supported in this browser.";
  }

  if (!("PushManager" in window)) {
    return "Push notifications are not supported in this browser.";
  }

  if (!("Notification" in window)) {
    return "Notifications are not supported in this browser.";
  }

  return "";
}

export function getPushConfigurationError() {
  return VAPID_PUBLIC_KEY ? "" : "Missing VITE_VAPID_PUBLIC_KEY.";
}

export async function registerPushNotifications(params: {
  userId: string;
  organizationId: string;
}) {
  const supportError = getPushSupportError();
  if (supportError) throw new Error(supportError);

  const configurationError = getPushConfigurationError();
  if (configurationError) throw new Error(configurationError);
  const vapidPublicKey = VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) throw new Error("Missing VITE_VAPID_PUBLIC_KEY.");

  const permission = await Notification.requestPermission();

  if (permission !== "granted") {
    throw new Error("Notification permission was not granted.");
  }

  await navigator.serviceWorker.register("/service-worker.js", {
    scope: "/",
  });

  const registration = await navigator.serviceWorker.ready;

  const existingSubscription = await registration.pushManager.getSubscription();

  const subscription =
    existingSubscription ??
    (await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
    }));

  const json = subscription.toJSON();

  if (!json.endpoint || !json.keys?.p256dh || !json.keys?.auth) {
    throw new Error("Invalid push subscription generated by browser.");
  }

  const { error } = await supabase.from("push_subscriptions").upsert(
    {
      organization_id: params.organizationId,
      user_id: params.userId,
      endpoint: json.endpoint,
      p256dh: json.keys.p256dh,
      auth: json.keys.auth,
      user_agent: navigator.userAgent,
      is_active: true,
    },
    {
      onConflict: "user_id,endpoint",
    },
  );

  if (error) throw error;

  return subscription;
}
